version: '3.9'
volumes:
  db:
    driver: local
services:
  mysqldb:
    image: mysql:latest
    container_name: gofit-mysql
    restart: always
    environment:
      MYSQL_DATABASE: gofit_db
      MYSQL_ROOT_PASSWORD: fikri1711
    ports:
      - "3306:3306"
    volumes:
      - db:/var/lib/mysql
    networks:
      - gonet

  app:
    build: 
      context: .
      dockerfile: Dockerfile
    container_name: gofit-app
    ports:
      - "8000:8000"
    restart: always
    volumes:
      - ./:/rest-api
    networks:
      - gonet
      
networks:
  gonet:
    driver: bridge